# Generated by Django 5.0.3 on 2024-04-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('via', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('car_name', models.CharField(max_length=100)),
                ('start_date_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
