# Generated by Django 5.0.3 on 2024-04-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carpool',
            new_name='Userdetails',
        ),
    ]
