# Generated by Django 5.0.3 on 2024-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
